spring:
  application:
    name: fisher-transaction-service
  cloud:
    nacos:
      config:
        server-addr: 192.168.222.130:8848
        file-extension: yml
        group: TSC_GROUP
  profiles:
    active: dev